package com.briup.apps.app02.bean;

public class StudentCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentCourse.id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentCourse.xk_time
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    private Long xkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentCourse.grade
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentCourse.student_id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentCourse.course_id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    private Long courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentCourse.id
     *
     * @return the value of studentCourse.id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentCourse.id
     *
     * @param id the value for studentCourse.id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentCourse.xk_time
     *
     * @return the value of studentCourse.xk_time
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public Long getXkTime() {
        return xkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentCourse.xk_time
     *
     * @param xkTime the value for studentCourse.xk_time
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public void setXkTime(Long xkTime) {
        this.xkTime = xkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentCourse.grade
     *
     * @return the value of studentCourse.grade
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentCourse.grade
     *
     * @param grade the value for studentCourse.grade
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentCourse.student_id
     *
     * @return the value of studentCourse.student_id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentCourse.student_id
     *
     * @param studentId the value for studentCourse.student_id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentCourse.course_id
     *
     * @return the value of studentCourse.course_id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentCourse.course_id
     *
     * @param courseId the value for studentCourse.course_id
     *
     * @mbg.generated Mon Jun 10 10:22:56 CST 2019
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }
}